# -----------------------------------------------------------------------------
# Grafana Cloud downstream tokens + SSM PS writeback (ADR-022)
# -----------------------------------------------------------------------------
# Two chains in this file:
#
#   1. Alloy — Cloud Access Policy (metrics:write, logs:write) scoped to this
#      stack's realm only, plus a token with 90-day expiry. Token value is
#      written to SSM PS for External Secrets Operator to sync into K8s.
#
#   2. grafana-operator — stack-level Service Account with Admin role, plus
#      a token with 90-day expiry. Stack Admin is required because
#      grafana-operator reconciles dashboards, contact points, notification
#      policies across the stack (ADR-023 §Decision — platform ownership of
#      the Grafana CRD). Token value written to SSM PS.
#
# Both tokens above are TF-generated by the grafana provider (Category B
# per ADR-028 §Out of scope). The SSM PS shell and the producer share a
# lifecycle owner; on workload teardown, both are destroyed together,
# and on next apply both regenerate. No persistence concern.
#
# Persistent SaaS-credential SSM PS shells (the bootstrap-token used by
# the grafana.cloud provider, and the team-webhooks-slack-aegis Slack
# webhook URL placeholder) live in the baseline-tier
# staging/secrets-persistent/ layer per ADR-028 — moved there after
# Incident 33 to prevent workload teardowns from destroying them.
#
# Why two different resource families for the two tokens:
#   - Alloy needs a stack-realm Cloud Access Policy — metrics/logs push
#     credentials live at the Cloud (org) API layer, not inside the stack.
#   - grafana-operator needs a stack Service Account — the Grafana API it
#     talks to (dashboards, alerting) is per-stack and authenticated by an
#     SA token minted inside the stack.
# Both are provisioned via the `cloud`-aliased grafana/grafana provider
# using the one-time bootstrap token in SSM PS.
#
# Token lifecycle: 90-day expiry per Runbook 006 §Token rotation. Rotation
# is a Terraform operation — edit `seconds_to_live` / `expires_at`, apply,
# External Secrets picks up the new values within its refresh interval.
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# Stack lookup — resolves the stack's region_slug for access-policy realm
# -----------------------------------------------------------------------------
# grafana_cloud_access_policy.realm needs the stack identifier. We look up
# the stack by its slug (from config.grafana_cloud.org_slug) so the realm
# entry is construction-safe against region drift (the stack's region is
# locked at creation and cannot change, but making the relationship data-
# sourced keeps the resource schema honest).
# -----------------------------------------------------------------------------

data "grafana_cloud_stack" "this" {
  count = local.observability_enabled ? 1 : 0

  provider = grafana.cloud

  slug = try(local.grafana_cloud.org_slug, "")
}

# -----------------------------------------------------------------------------
# Alloy — Cloud Access Policy + token
# -----------------------------------------------------------------------------

resource "grafana_cloud_access_policy" "alloy" {
  count = local.observability_enabled ? 1 : 0

  provider = grafana.cloud

  region       = data.grafana_cloud_stack.this[0].region_slug
  name         = "aegis-staging-alloy"
  display_name = "Alloy — metrics and logs push from aegis-staging clusters"

  scopes = ["metrics:write", "logs:write"]

  realm {
    type       = "stack"
    identifier = data.grafana_cloud_stack.this[0].id
  }
}

resource "grafana_cloud_access_policy_token" "alloy" {
  count = local.observability_enabled ? 1 : 0

  provider = grafana.cloud

  region           = data.grafana_cloud_stack.this[0].region_slug
  access_policy_id = grafana_cloud_access_policy.alloy[0].policy_id
  name             = "aegis-staging-alloy"
  display_name     = "Alloy 90-day rotating token"
  # 90-day expiry per Runbook 006 §Token rotation. Bump this timestamp on
  # rotation — new token value materialises and SSM PS updates in-place.
  expires_at = "2026-07-20T00:00:00Z"
}

# -----------------------------------------------------------------------------
# grafana-operator — Stack Service Account + token
# -----------------------------------------------------------------------------

resource "grafana_cloud_stack_service_account" "grafana_operator" {
  count = local.observability_enabled ? 1 : 0

  provider = grafana.cloud

  stack_slug = try(local.grafana_cloud.org_slug, "")
  name       = "grafana-operator"
  role       = "Admin"
}

resource "grafana_cloud_stack_service_account_token" "grafana_operator" {
  count = local.observability_enabled ? 1 : 0

  provider = grafana.cloud

  stack_slug         = try(local.grafana_cloud.org_slug, "")
  service_account_id = grafana_cloud_stack_service_account.grafana_operator[0].id
  name               = "grafana-operator-terraform"
  # 90 days = 7,776,000 seconds. Matches Alloy's rotation cadence.
  seconds_to_live = 7776000
}

# -----------------------------------------------------------------------------
# SSM PS writeback — downstream tokens
# -----------------------------------------------------------------------------
# Each token is stored as a SecureString encrypted with the shared secrets
# CMK (alias/aegis-staging-secrets). External Secrets Operator (installed in
# staging/platform) reads these parameters via the aegis-ssm
# ClusterSecretStore and reconciles them into K8s Secrets on each cluster.
# -----------------------------------------------------------------------------

resource "aws_ssm_parameter" "alloy_token" {
  count = local.observability_enabled ? 1 : 0

  name        = "${local.ssm_path_prefix}/alloy-token"
  description = "Grafana Cloud Alloy remote_write token. Provisioned by terraform/environments/staging/observability/; consumed by ExternalSecret → K8s Secret `alloy-token` in ns `monitoring`, mounted as env GRAFANA_CLOUD_TOKEN by the Alloy Deployment (staging/platform)."
  type        = "SecureString"
  key_id      = data.aws_kms_alias.secrets[0].target_key_arn
  value       = grafana_cloud_access_policy_token.alloy[0].token

  tags = merge(local.tags, {
    Name = "grafana-cloud-alloy-token"
  })
}

resource "aws_ssm_parameter" "grafana_operator_token" {
  count = local.observability_enabled ? 1 : 0

  name        = "${local.ssm_path_prefix}/grafana-operator-token"
  description = "Grafana Cloud stack Service Account token (Admin role). Provisioned by terraform/environments/staging/observability/; consumed by ExternalSecret → K8s Secret `grafana-operator-token` in ns `observability`, referenced by the Grafana CRD's spec.external.apiKey."
  type        = "SecureString"
  key_id      = data.aws_kms_alias.secrets[0].target_key_arn
  value       = grafana_cloud_stack_service_account_token.grafana_operator[0].key

  tags = merge(local.tags, {
    Name = "grafana-cloud-grafana-operator-token"
  })
}

# -----------------------------------------------------------------------------
# Persistent Path-B SSM PS shells moved to staging/secrets-persistent/ (ADR-028)
# -----------------------------------------------------------------------------
# Pre-2026-04-25 this file owned `team_webhooks_slack_aegis` (the Slack
# webhook URL placeholder for aegis-core's GrafanaContactPoint CRD per
# ldz #126). The bootstrap-token was also adjacent — read-only data
# source in config.tf, but operator-managed in AWS via Runbook 006
# §Part 2.
#
# Both moved to the baseline-tier staging/secrets-persistent/ layer
# after Incident 33's teardown destroyed the qdrant SSM values (which
# had `lifecycle.ignore_changes = [value]` — Incident 34 documents that
# this block does not protect against destroy). The persistent SaaS-
# credential isolation pattern in ADR-028 enumerates the 4-resource
# scope: bootstrap-token, team-webhooks-slack-aegis, qdrant-cloud/
# cluster-url, qdrant-cloud/api-key.
#
# The ExternalSecret CRD that consumes team-webhooks-slack-aegis at
# runtime stays in this layer (external-secrets.tf) — it targets the
# `aegis` namespace owned by staging/workloads and uses the kubectl
# provider already wired here. The data source for bootstrap-token also
# stays in this layer (config.tf), reading the SSM PS by path string —
# unaffected by which Terraform state owns the resource shell.
# -----------------------------------------------------------------------------
